// Generated by CoffeeScript 1.5.0
(function() {
  var SomeUsefulFunction;

  SomeUsefulFunction = function(msg) {
    return console.log(msg);
  };

  $(function() {
    var hello;
    hello = 'Hello World!';
    return SomeUsefulFunction(hello);
  });

}).call(this);
